# Generated by Django 5.2.5 on 2025-08-20 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionresult',
            old_name='processed_at',
            new_name='detected_at',
        ),
        migrations.RemoveField(
            model_name='audioarchive',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='detectionresult',
            name='detected_instrument',
        ),
        migrations.AddField(
            model_name='audioarchive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.instrument'),
        ),
        migrations.AlterField(
            model_name='audioarchive',
            name='file',
            field=models.FileField(upload_to='archives/'),
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chunks/')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.audioarchive')),
            ],
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='audio_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.audiofile'),
        ),
    ]
